# The public documentation URL, used for sitemap.xml
url: "https://docs.telerik.com/blazor-ui"

all_pages_domain: "https://docs.telerik.com"

capital_casing_redirects: true

# Exclude files which should not be in the output
exclude: [README.md, Gemfile, Gemfile.lock,api_sort.rb, Dockerfile, bs-config.js, build-docs.sh, copy_content.sh, copy_local.sh, docs-watcher/*, exclude_files.txt, install-npm.sh, start-docs.sh, watch.sh]
exclude_navigation: ["knowledge-base/*"]
navigation:

## List your directory names and order here, like this:

     "knowledge-base":
        title: "Knowledge Base"
        position: 40
     "api":
        title: "API Reference"
        position: 0
     "getting-started":
        title: "Getting Started"
        position: 5
     "installation":
        title: "Installation"
        position: 6
     "components":
        title: "Components"
        position: 10
     "themes":
        title: "Themes"
        position: 12
     "common-features":
        title: "Common Features"
        position: 15
     "globalization":
        title: "Globalization"
        position: 16
     "accessibility":
        title: "Accessibility"
        position: 17
     "upgrade":
        title: "Upgrade"
        position: 18
     "upgrade/breaking-changes":
        title: "Breaking Changes"
     "how-to":
        title: "How To"
        position: 20
     "getting-started/vs-integration":
        title: "Visual Studio Integration"
        position: 25
     "getting-started/vs-code-integration":
        title: "Visual Studio Code Integration"
        position: 26
     "backwards-compatibility":
        title: "Breaking Changes"
        position: 30

## List custom TOC order for folders here

     "*components/grid/columns":
        title: "Columns"
        position: 5
     "*components/grid/editing":
        title: "Editing"
        position: 10
     "*components/grid/templates":
        title: "Templates"
        position: 25
     "*components/grid/export":
        title: "Export"
        position: 30
     "*components/grid/selection":
        title: "Selection"
        position: 35
     "*components/treelist/data-binding":
        title: "Data Binding"
        position: 2
     "*components/treelist/columns":
        title: "Columns"
        position: 5
     "*components/treelist/editing":
        title: "Editing"
        position: 10
     "*components/treelist/templates":
        title: "Templates"
        position: 25
     "*components/treelist/export":
        title: "Export"
        position: 30
     "*components/treelist/selection":
        title: "Selection"
        position: 35
     "*components/chart/types":
        title: "Types"
        position: 15
     "*components/chart/tooltip":
        title: "Tooltips"
        position: 32
     "*components/stockchart/types":
        title: "Types"
        position: 12
     "*components/stockchart/tooltip":
        title: "Tooltips"
        position: 22
     "*components/animationcontainer":
        title: "Animation Container"
        position: 2000000
     "*components/treeview/data-binding":
        title: "Data Binding"
        position: 2
     "*components/treeview/selection":
        title: "Selection"
        position: 3
     "*components/contextmenu/data-binding":
        title: "Data Binding"
        position: 2
     "*components/contextmenu/templates":
        title: "Templates"
        position: 25
     "*components/menu/data-binding":
        title: "Data Binding"
        position: 2
     "*components/scheduler/appointments":
        title: "Appointments"
        position: 2
     "*components/scheduler/views":
        title: "Views"
        position: 5

## List helpers directory names and order here, like this:
     "*appearance":
        title: "Appearance"
     "*binding":
        title: "Binding"
        position: 2
     "*troubleshooting":
        title: "Troubleshooting"
        position: 50
     "*editing":
        title: "Editing"
     "*export":
        title: "Export"
     "*filtering":
        title: "Filtering"
     "*integration":
        title: "Integration"
     "*selection":
        title: "Selection"
     "*state":
        title: "State Management"
     "*how-to":
        title: "How To"
     "*grid":
        title: "Grid"
     "*listview":
        title: "ListView"
     "*treelist":
        title: "TreeList"
     "*spreadsheet":
        title: "Spreadsheet"
     "*arcgauge":
        title: "ArcGauge"
     "*autocomplete":
        title: "AutoComplete"
     "*barcode":
        title: "BarCode"
     "*togglebutton":
        title: "ToggleButton"
     "*button":
        title: "Button"
     "*buttongroup":
        title: "ButtonGroup"
     "html-helpers/scheduling/calendar":
        title: "Calendar"
     "html-helpers/scheduling/multiviewcalendar":
        title: "MultiViewCalendar"
     "tag-helpers/scheduling/multiviewcalendar":
        title: "MultiViewCalendar"
     "*calendar":
        title: "Calendar"
     "*chart":
        title: "Chart"
     "*checkbox":
        title: "Checkbox"
     "*colorpalette":
        title: "ColorPalette"
     "*colorpicker":
        title: "ColorPicker"
     "*/multicolumncombobox":
        isNew: true
        title: "MultiColumnComboBox"
     "*combobox":
        title: "ComboBox"
     "*contextmenu":
        title: "Context Menu"
     "*dateinput":
        title: "Date Input"
     "*datepicker":
        title: "Date Picker"
     "*daterangepicker":
        title: "DateRange Picker"
     "*datetimepicker":
        title: "DateTime Picker"
     "*dialog":
        title: "Dialog"
     "*draganddrop":
        title: "DragAndDrop"
     "*drawer":
        title: "Drawer"
     "*dropdownlist":
        title: "DropDownList"
     "*dropdowntree":
        isNew: true
        title: "DropDownTree"
     "*editor":
        title: "Editor"
     "*flatcolorpicker":
        title: "FlatColorPicker"
     "*gantt":
        title: "Gantt"
     "*lineargauge":
        title: "LinearGauge"
     "*listbox":
        title: "ListBox"
     "*map":
        title: "Map"
     "*maskedtextbox":
        title: "MaskedTextBox"
     "*mediaplayer":
        title: "MediaPlayer"
     "*menu":
        title: "Menu"
     "*multiselect":
        title: "MultiSelect"
     "*notification":
        title: "Notification"
     "*popup":
        title: "Popup"
     "*numerictextbox":
        title: "NumericTextBox"
     "*progressbar":
        title: "ProgressBar"
     "*qrcode":
        title: "QRCode"
     "*/radiobutton":
        title: "RadioButton"
     "*radialgauge":
        title: "RadialGauge"
     "*rangeslider":
        title: "RangeSlider"
     "*responsivepanel":
        title: "ResponsivePanel"
     "*panelbar":
        title: "PanelBar"
     "*pager":
        title: "Pager"
     "*pivotgrid":
        title: "PivotGrid"
     "*scheduler":
        title: "Scheduler"
     "*scrollview":
        title: "ScrollView"
     "*slider":
        title: "Slider"
     "*sortable":
        title: "Sortable"
     "*splitter":
        title: "Splitter"
      "*stockchart":
        title: "StockChart"
     "*tabstrip":
        title: "TabStrip"
     "*textbox":
        title: "TextBox"
     "*timepicker":
        title: "TimePicker"
     "*tooltip":
        title: "Tooltip"
     "*toolbar":
        title: "ToolBar"
     "*treelist":
        title: "TreeList"
     "*treeview":
        title: "TreeView"
     "*treemap":
        title: "TreeMap"
     "*upload":
        title: "Upload"
     "*validator":
        title: "Validator"
     "*window":
        title: "Window"
     "*templates":
        title: "Templates"
     "*switch":
        title: "Switch"

## introduction article columns. Use the slugs in the items collection

api_reference_url: "api/"

intro_columns:
-
  categories:
  -
    title: "Data Management"
    items:
      "Grid": "components/grid/overview"
      "TreeList": "treelist-overview"
      "ListView": "listview-overview"

  -
    title: "Navigation"
    items:
      "Button": "components/button/overview"
      "Toggle Button": "togglebutton-overview"
      "Button Group" : "buttongroup-overview"
      "Menu": "components/menu/overview"
      "Context Menu": "contextmenu-overview"
      "Tab Strip": "components/tabstrip/overview"
      "TreeView": "components/treeview/overview"
      "Pager": "pager-overview"

-
  categories:
  -
    title: "Editors"
    items:
      "Textbox": "components/textbox/overview"
      "Numeric Textbox": "components/numerictextbox/overview"
      "Date Input": "components/dateinput/overview"
      "Date Picker": "components/datepicker/overview"
      "Time Picker": "components/timepicker/overview"
      "DateTime Picker": "components/datetimepicker/overview"
      "DateRange Picker": "daterangepicker-overview"
      "DropDownList": "components/dropdownlist/overview"
      "ComboBox": "components/combobox/overview"
      "AutoComplete": "autocomplete-overview"
      "MultiSelect": "multiselect-overview"
      "CheckBox": "checkbox-overview"

-
  categories:
  -
    title: "Data Visualization"
    items:
      "Charts Overview": "components/chart/overview"
      "Area Charts": "components/chart/types/area"
      "Column Charts": "components/chart/types/column"
      "Bar Charts": "components/chart/types/bar"
      "Line Charts": "components/chart/types/line"
      "Pie Charts": "components/chart/types/pie"
      "Donut Charts": "components/chart/types/donut"
      "Bubble Charts": "components/chart/types/bubble"
      "Scatter Charts": "components/chart/types/scatter"
      "ScatterLine Charts": "components/chart/types/scatterline"
  -

-
  categories:
  -
    title: "Files"
    items:
      "File Upload": "upload-overview"
  -
    title: "Layout"
    items:
      "Window": "components/window/overview"
      "Animation Container": "components/animationcontainer/overview"
      "Tooltip": "tooltip-overview"
      "Drawer": "drawer-overview"
  -
    title: "Scheduling"
    items:
      "Scheduler": "scheduler-overview"
      "Calendar": "components/calendar/overview"



## The application virtual path
baseurl: /blazor-ui

## Latest UI for Blazor version. Used in some articles
uiForBlazorLatestVersion: "2.15.0"
supportedFrameworkVersion: ".NET Core 3.1.4"

## The Kendo UI version used
cdnVersion: "2019.1.115"

## The MVC Core version used
mvcCoreVersion: "2019.1.115"

## Product
product: "Telerik UI for Blazor"
platform: blazor

## Assign layout and category per different paths
defaults:
-
    scope:
        path: ""
    values:
        layout: "documentation"
        category: "default"
        product: "blazor"
        editable: true
        description_suffix: "Read more in Telerik UI for Blazor Documentation."
-
    scope:
        path: "blazor"
    values:
        product: "blazor"
-
    scope:
        path: "api"
    values:
        editable: false
        res_type: api
        kind: api
-
    scope:
        path: "components"
    values:
        title_prefix: "Blazor"
        title_prefix_separator: " "
-
    scope:
        path: "themes"
    values:
        title_prefix: "Blazor"
        title_prefix_separator: " "
-
    scope:
        path: "common-features"
    values:
        title_prefix: "Blazor"
        title_prefix_separator: " "
-
    scope:
        path: "globalization"
    values:
        title_prefix: "Blazor"
        title_prefix_separator: " "
-
    scope:
        path: "accessibility"
    values:
        title_prefix: "Blazor"
        title_prefix_separator: " "
-
    scope:
        path: "themes"
    values:
        title_prefix: "Blazor"
        title_prefix_separator: " "
-
    scope:
        path: "knowledge-base"
    values:
        layout: "documentation"
        category: "default"
        product: "blazor"
        editable: true
        description_suffix: "Read more in our Blazor Knowledgebase articles."

#type_links:
#    "kendo.Class": "/api/javascript/class"
#    "kendo.data.DataSource": "/api/javascript/data/datasource"
#    "Array": "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array"
#    "Blob": "https://developer.mozilla.org/en/docs/Web/API/Blob"
#    "File": "https://developer.mozilla.org/en-US/docs/Web/API/File"
#    "Boolean": "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean"
#    "Function": "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function"
#    "jQuery": "http://api.jquery.com/Types/#jQuery"
#    "Promise": "http://api.jquery.com/Types/#Promise"
#    "Object": "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object"
#    "Number": "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number"
#    "String": "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String"

# Aliases available in the markdown template. The below will expand {{site.foo}} to Bar in the output
# "foo": "Bar"

# The google services configuration
google_tag_manager: GTM-6X92
gcs_engine: 001595215763381649090:3v0klcxtf1c
gcs_api_key: AIzaSyDqCekEzmMvnB7i00Xcw_Vy43a7-wePuXQ
#Feedback Form Google Sheet ID
ff-sheet-id: 0c41d166-7ba6-3500-20d5-609d41442f92

# improved feedback form
feedback_ab: true

# other settings
skip_tabbed_code: true
code_lang: true
has_kb_portal: true
edit_repo_url: https://github.com/telerik/blazor-docs/edit/master
product_url: https://www.telerik.com/blazor-ui
download: https://www.telerik.com/download-trial-file/v2-b/ui-for-blazor


footer:
-
  title: "Getting Started"
  links:
    "Client-side Blazor": https://docs.telerik.com/blazor-ui/getting-started/client-blazor
    "Server-side Blazor": https://docs.telerik.com/blazor-ui/getting-started/server-blazor
    "Blazor Introduction Videos" : https://www.youtube.com/watch?v=aaRAZYaJ4xc&list=PLvmaC-XMqeBYPTwcm478vs8Rujq2tiVJo

-
  title: "Community"
  links:
    "Forums": https://www.telerik.com/forums/blazor
    "Blogs": https://www.telerik.com/blogs/tag/blazor
    "Feedback Portal": https://feedback.telerik.com/blazor

-
  title: "Support Resources"
  links:
    "Demos": https://demos.telerik.com/blazor-ui
    "Knowledge Base": https://docs.telerik.com/blazor-ui/knowledge-base
    "Samples Repo": https://github.com/telerik/blazor-ui

-
  title: "Sample Applications"
  links:
    "Dashboard": https://demos.telerik.com/blazor-dashboard-app/
    "PWA - Stocks": https://demos.telerik.com/blazor-financial-portfolio


footer_social:
    facebook: https://www.facebook.com/Telerik/
    youtube: https://www.youtube.com/user/TelerikInc
    linkedin: https://www.linkedin.com/showcase/telerik/
    twitter: https://twitter.com/Telerik/

# Assets pipeline configuration
use_cachebusting: false
# These may be obsolete, but avoid touching just in case
assets:
    cachebust: soft
    js_compressor: uglifier
    gzip: false

## Do not edit below this line
safe: false
markdown: MarkdownProcessor
