title: Wai-Aria Support
component: AutoComplete
from: /aria/autocomplete_aria.md
dest: ../components/autocomplete/accessibility/wai-aria-support.md
slug: autocomplete-wai-aria-support
position: 50
after:  |
    ## Keyboard Navigation

    For details on how the AutoComplete keyboard navigation works, refer to the [Blazor AutoComplete Accessibility and Keyboard Navigation Demo](https://demos.telerik.com/blazor-ui/autocomplete/keyboard-navigation).

    ## See Also

    * [Accessibility in Telerik UI for Blazor](slug://accessibility-overview)
