title: Wai-Aria Support
component: Dialog
from: /aria/dialog_aria.md
dest: ../components/dialog/accessibility/wai-aria-support.md
slug: dialog-wai-aria-support
position: 50
after:  |
    ## Keyboard Navigation

    For details on how the keyboard navigation works in Telerik UI for Blazor, refer to the [Accessibility Overview](slug:accessibility-overview#keyboard-navigation) article.

    ## See Also

    * [Blazor Dialog Demos](https://demos.telerik.com/blazor-ui/dialog/overview)
    * [Accessibility in Telerik UI for Blazor](slug:accessibility-overview)
