title: Wai-Aria Support
component: Slider
from: /aria/slider_aria.md
dest: ../components/slider/accessibility/wai-aria-support.md
slug: slider-wai-aria-support
position: 50
after:  |
    ## Keyboard Navigation

    For details on how the Slider keyboard navigation works, refer to the [Blazor Slider Accessibility and Keyboard Navigation Demo](https://demos.telerik.com/blazor-ui/slider/keyboard-navigation).

    ## See Also

    * [Accessibility in Telerik UI for Blazor](slug:accessibility-overview)
