title: Wai-Aria Support
component: TextBox
from: /aria/textbox_aria.md
dest: ../components/textbox/accessibility/wai-aria-support.md
slug: textbox-wai-aria-support
position: 50
after:  |
    ## Keyboard Navigation

    For details on how the keyboard navigation works in Telerik UI for Blazor, refer to the [Accessibility Overview]({%slug accessibility-overview%}#keyboard-navigation) article.

    ## See Also

    * [Blazor TextBox Demos](https://demos.telerik.com/blazor-ui/textbox/overview)
    * [Accessibility in Telerik UI for Blazor]({%slug accessibility-overview%})
